# Locally override default configurations
#
# This file overrides configurations set in `config/config.defaults.yml`.
# Keep in mind that environment variables override setting in this file.
#
# Usage:
#
# Copy this file from `config/config.example.yml` to `config/config.yml`
#

default:

development:
  # Add local `development` environment configuration overrides here
  

test:
  # Add local `test` environment configuration overrides here

staging:
  # Add local `staging` environment configuration overrides here
  aws_access_key_id: AKIAIEM5KQAJ2RM4H5LA
  aws_secret_access_key: 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
  s3_bucket_name: cyclelifehq-staging-images
  s3_upload_bucket_name: cyclelifehq-staging-images-tmp
 


production:
  # Add local `production` environment configuration overrides here
